### ISSUE TITLE
Running/developing on Windows? 

### ISSUE THREAD

**Issue by Claxtastic** [jamesridgway/devdeck#11]
First I just want to say I came across this from your YouTube video and it's an awesome project. I was wondering though if it works/could work on Windows. My (limited) understanding of the project is that it should be able to run on Windows, but I haven't yet gotten it working.

I also haven't worked with Python in awhile, so sorry if I'm missing something basic. As it stands after I've downloaded the repo, I've tried running devdeck.py, but I get an error on some of the imports:
`PS C:\Repos\devdeck\devdeck> python .\devdeck.py
Traceback (most recent call last):
  File "C:\Repos\devdeck\devdeck\devdeck.py", line 3, in <module>
    from devdeck.deck_context import DeckContext
  File "C:\Repos\devdeck\devdeck\devdeck.py", line 3, in <module>
    from devdeck.deck_context import DeckContext
ModuleNotFoundError: No module named 'devdeck.deck_context'; 'devdeck' is not a package`

That doesn't seem to be related to running in the Windows environment, but I wanted to post this issue as a broader conversation of whether this does/can work on Windows.

Thanks

**Comment by jamesridgway** [comment]
Hey,

I didn't specifically target windows as I figured most windows users would be content with the official Elgato software, however I'm happy to get it working on Windows if there is an apetite, which it sounds like there is.

So in theory the bulk of it should work on Windows, the only things that definitely won't are the audio controls for volume and muting as those are OS specfic, but there is no reason why they shouldn't work.

I'll look into what it will take to get this working on Windows.

**Comment by jamesridgway** [comment]
I think I've figured out the cause of this and am working on an update to address the isses.

**Comment by jamesridgway** [comment]
Version 1.0.12+ now supports Windows.

The [installation instructions](https://github.com/jamesridgway/devdeck/wiki/Installation) have also been updated as you will need to install libUSB DLLs
