### ISSUE TITLE
Need another udev rule for Streamdeck MK2

### ISSUE THREAD

**Issue by nicdumz** [jamesridgway/devdeck#14]
Product Id for Stream Deck MK2 is `0080`, so I believe the wiki page should be updated to also include:

`SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", MODE:="660", GROUP="plugdev"`

Thanks!

**Comment by jamesridgway** [comment]
Thanks @nicdumz  . Wiki updated
