### ISSUE TITLE
README points to https://files.james-ridgway.co.uk which has an expired SSL cert

### ISSUE THREAD

**Issue by nicdumz** [jamesridgway/devdeck#15]
Heya,

The readme links to https://files.james-ridgway.co.uk/images/streamdeck-yt-thumbnail.png which gives an HTTPS cert error (security certificate expired 99 days ago).

You might want to either renew your cert; alternatively you could consider including the thumbnail in the repo itself.

Cheers!

**Comment by jamesridgway** [comment]
Thanks, fixed.
