### ISSUE TITLE
Add 'devdeck' tag to all devdeck- related repos?

### ISSUE THREAD

**Issue by nicdumz** [jamesridgway/devdeck#16]
Heya,

I wonder if it'd make sense to add a 'devdeck' [topic tag](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) to all devdeck repos to make them searchable via https://github.com/topics/devdeck . This way you could link existing plugins from https://github.com/jamesridgway/devdeck#plugins for instance?

As a heads-up, too, I have forked https://github.com/jamesridgway/devdeck-key-light into https://github.com/nicdumz/devdeck-hue (support for Philips Hue lights).

Cheers!

**Comment by jamesridgway** [comment]
Thanks for the suggestion @nicdumz - this has now been done.
