### ISSUE TITLE
Raspberry Pi OS

### ISSUE THREAD

**Issue by RashKash103** [jamesridgway/devdeck#2]
Hi @jamesridgway! First things first, awesome project you got here, really loving it! 

I've installed devdeck on a Raspberry Pi 4 and I needed to take a couple of extra steps to get it working. Wanted to share these with you so you can perhaps add them to the wiki so others who try to get it running have fewer issues!

Basically, after running `pip install devdeck`, you need to install a couple more things on the Raspberry Pi. The errors that would be displayed when attempting to run `devdeck` would be
- `ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory`
- `ImportError: libtiff.so.5: cannot open shared object file: No such file or directory`

To fix those errors, these need to be installed:
`sudo apt install -y libopenjp2-7 libtiff5`

I've only tested this on the Raspberry Pi 4 and thus wouldn't be able to say if this works on earlier models or the Pi Zeros but I'd be surprised if it didn't.

Again, great job here, it's really going to pull together my Home Assistant setup! 😃

**Comment by jamesridgway** [comment]
Hi @RashKash103 

Glad to hear that you're enjoying the project! And thank you for your additions!

I've now taken the time to update the wiki to include your installation steps:
https://github.com/jamesridgway/devdeck/wiki/Installation

Thanks!
