### ISSUE TITLE
devdeck core dumps (Ubuntu Mate 20.04)

### ISSUE THREAD

**Issue by frodonl** [jamesridgway/devdeck#3]
Whenever I try to start devdeck it clears the display on my Stream Deck and then core dumps:

```
2021-03-16 19:35:40,240 - devdeck - INFO - Connecting to deck: b'0001:0010:00' (S/N: AL49J2C06472)
2021-03-16 19:35:40,244 - devdeck - INFO - Setting active deck: SinglePageDeckController
2021-03-16 19:35:40,244 - devdeck - INFO - Rendering deck: SinglePageDeckController
realloc(): invalid next size
Aborted (core dumped)
```

This is running devdeck-1.0.5 on Ubuntu 20.04, using Python 3.8.5, using the default small setting.yml (with just ClockControl on key 0).

**Comment by jamesridgway** [comment]
Hi @frodonl

Which stream deck do you have?

**Comment by frodonl** [comment]
Hi @jamesridgway it was a Stream Deck V2 (which, I'm afraid to say, I returned already earlier today, since it turned out this issue didn't just happen with devdeck but also with any other Linux tool I tried).

**Comment by jamesridgway** [comment]
I'll close this on the basis this sounds like a device issue.
