### ISSUE TITLE
Long running commands kill devdeck

### ISSUE THREAD

**Issue by DeastinY** [jamesridgway/devdeck#7]
I've created a command to start a gnome-terminal and run my vpn program.
Afterwards I can't use the stream deck anymore and everything freezes :D

**Comment by jamesridgway** [comment]
I have taken a look at this and `CommandControl` is using `Popen` to spawn the command which is non-blocking by default.

In my testing I did find that if the command is wrong and does not exist a `FileNotFoundError` will be thrown which isn't handled and causes devdeck to crash - this results in the same symptom you've described ("can't use the stream deck anymore and everything freezes").

I have pushed an update that incorporates better error handling - #9 

I will release this as 1.0.10

Logs will now also be written to `~/.devdeck/devdeck.log`

**Comment by jamesridgway** [comment]
1.0.10 has now been released

**Comment by DeastinY** [comment]
thanks for looking into it!
